image: microsoft/dotnet:2-sdk

stages:
- build
- publish

build:
  stage: build
  script:
  - dotnet build
  - dotnet pack -c Release --include-symbols -p:SymbolPackageFormat=snupkg -o $CI_PROJECT_DIR/Build/
  artifacts:
    paths:
    - Build/*.nupkg
    - Build/*.snupkg
    expire_in: 1 week

publish:
  stage: publish
  when: manual
  script:
  - cd $CI_PROJECT_DIR/Build/
  - nuget SetApiKey $NUGET_KEY
  - dotnet nuget push *.nupkg
  - dotnet nuget push *.snupkg
  dependencies:
  - build