//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.206.0.
namespace MBW.Clients.Rejseplanen.Schema.RestLocation
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>The location list contains either named coordinates or stops/stations with name and id as a result of a location request. The data of every list entry can be used for further trip or departureBoard requests.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The location list contains either named coordinates or stops/stations with name a" +
        "nd id as a result of a location request. The data of every list entry can be use" +
        "d for further trip or departureBoard requests.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocationList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("LocationList", Namespace="")]
    public partial class LocationList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<StopLocation> _stopLocation;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("StopLocation", Namespace="")]
        public System.Collections.ObjectModel.Collection<StopLocation> StopLocation
        {
            get
            {
                return this._stopLocation;
            }
            private set
            {
                this._stopLocation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die StopLocation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the StopLocation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StopLocationSpecified
        {
            get
            {
                return (this.StopLocation.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="LocationList" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="LocationList" /> class.</para>
        /// </summary>
        public LocationList()
        {
            this._stopLocation = new System.Collections.ObjectModel.Collection<StopLocation>();
            this._coordLocation = new System.Collections.ObjectModel.Collection<CoordLocation>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CoordLocation> _coordLocation;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("CoordLocation", Namespace="")]
        public System.Collections.ObjectModel.Collection<CoordLocation> CoordLocation
        {
            get
            {
                return this._coordLocation;
            }
            private set
            {
                this._coordLocation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die CoordLocation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the CoordLocation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoordLocationSpecified
        {
            get
            {
                return (this.CoordLocation.Count != 0);
            }
        }
    }
    
    /// <summary>
    /// <para>The element StopLocation specifies  a stop/station in a result of a location request. It contains an output name and an id.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The element StopLocation specifies a stop/station in a result of a location reque" +
        "st. It contains an output name and an id.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StopLocation", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("StopLocation", Namespace="")]
    public partial class StopLocation : IAttlistPeriodStopLocation
    {
        
        /// <summary>
        /// <para>Contains the output name of this stop or station</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the output name of this stop or station")]
        [System.Xml.Serialization.XmlAttributeAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>The WGS84 x coordinate as integer (multiplied by 1,000,000)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The WGS84 x coordinate as integer (multiplied by 1,000,000)")]
        [System.Xml.Serialization.XmlAttributeAttribute("x", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int X { get; set; }
        
        /// <summary>
        /// <para>The WGS84 y coordinate as integer (multiplied by 1,000,000)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The WGS84 y coordinate as integer (multiplied by 1,000,000)")]
        [System.Xml.Serialization.XmlAttributeAttribute("y", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Y { get; set; }
        
        /// <summary>
        /// <para>This ID can either be used as originId or destId to perform a trip request or to call a departure  board.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("This ID can either be used as originId or destId to perform a trip request or to " +
            "call a departure board.")]
        [System.Xml.Serialization.XmlAttributeAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodStopLocation
    {
        
        /// <summary>
        /// <para>Contains the output name of this stop or station</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the output name of this stop or station")]
        string Name
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>The WGS84 x coordinate as integer (multiplied by 1,000,000)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The WGS84 x coordinate as integer (multiplied by 1,000,000)")]
        int X
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>The WGS84 y coordinate as integer (multiplied by 1,000,000)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The WGS84 y coordinate as integer (multiplied by 1,000,000)")]
        int Y
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>This ID can either be used as originId or destId to perform a trip request or to call a departure  board.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("This ID can either be used as originId or destId to perform a trip request or to " +
            "call a departure board.")]
        string Id
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// <para>The element CoordLocation specifies a coordinate based location in a result of a location request. It contains an output name, x-coordinate, y coordinate and a  type (address or point of interest). The coordinates and the name can be used as origin or destination parameters to perform a trip request.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"The element CoordLocation specifies a coordinate based location in a result of a location request. It contains an output name, x-coordinate, y coordinate and a type (address or point of interest). The coordinates and the name can be used as origin or destination parameters to perform a trip request.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CoordLocation", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CoordLocation", Namespace="")]
    public partial class CoordLocation : IAttlistPeriodCoordLocation
    {
        
        /// <summary>
        /// <para>The WGS84 x coordinate as integer (multiplied by 1,000,000)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The WGS84 x coordinate as integer (multiplied by 1,000,000)")]
        [System.Xml.Serialization.XmlAttributeAttribute("x", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int X { get; set; }
        
        /// <summary>
        /// <para>The WGS84 y coordinate as integer (multiplied by 1,000,000)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The WGS84 y coordinate as integer (multiplied by 1,000,000)")]
        [System.Xml.Serialization.XmlAttributeAttribute("y", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Y { get; set; }
        
        /// <summary>
        /// <para>Contains the output name of the address or point of interest</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the output name of the address or point of interest")]
        [System.Xml.Serialization.XmlAttributeAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>The attribute type specifies the type of location. Valid values are ADR (address) or POI (point of interest). This attribute can be used to do some sort of classification in the user interface. For later trip requests it does not have any meaning.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The attribute type specifies the type of location. Valid values are ADR (address)" +
            " or POI (point of interest). This attribute can be used to do some sort of class" +
            "ification in the user interface. For later trip requests it does not have any me" +
            "aning.")]
        [System.Xml.Serialization.XmlAttributeAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IAttlistPeriodCoordLocationType Type { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodCoordLocation
    {
        
        /// <summary>
        /// <para>The WGS84 x coordinate as integer (multiplied by 1,000,000)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The WGS84 x coordinate as integer (multiplied by 1,000,000)")]
        int X
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>The WGS84 y coordinate as integer (multiplied by 1,000,000)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The WGS84 y coordinate as integer (multiplied by 1,000,000)")]
        int Y
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Contains the output name of the address or point of interest</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the output name of the address or point of interest")]
        string Name
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>The attribute type specifies the type of location. Valid values are ADR (address) or POI (point of interest). This attribute can be used to do some sort of classification in the user interface. For later trip requests it does not have any meaning.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The attribute type specifies the type of location. Valid values are ADR (address)" +
            " or POI (point of interest). This attribute can be used to do some sort of class" +
            "ification in the user interface. For later trip requests it does not have any me" +
            "aning.")]
        IAttlistPeriodCoordLocationType Type
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IAttlistPeriodCoordLocationType", Namespace="")]
    public enum IAttlistPeriodCoordLocationType
    {
        
        /// <summary>
        /// </summary>
        ADR,
        
        /// <summary>
        /// </summary>
        POI,
    }
}
