//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.206.0.
namespace MBW.Clients.Rejseplanen.Schema.RestTrip
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Origin of a leg including location name, location type, location route index (if available), departure time and date, realtime departure (if available), track and realtime track (if available)</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Origin of a leg including location name, location type, location route index (if " +
        "available), departure time and date, realtime departure (if available), track an" +
        "d realtime track (if available)")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OriginDestType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Origin", Namespace="")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Destination))]
    public partial class OriginDestType : IAttlistPeriodOriginDestType
    {
        
        /// <summary>
        /// <para>Contains the name of the location.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the name of the location.")]
        [System.Xml.Serialization.XmlAttributeAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>The attribute type specifies the type of location. Valid values are ST (stop/station), ADR (address) or POI (point of interest). This attribute can be used to do some sort of classification in the user interface. For later trip requests it does not have any meaning.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"The attribute type specifies the type of location. Valid values are ST (stop/station), ADR (address) or POI (point of interest). This attribute can be used to do some sort of classification in the user interface. For later trip requests it does not have any meaning.")]
        [System.Xml.Serialization.XmlAttributeAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IAttlistPeriodOriginDestTypeType Type { get; set; }
        
        /// <summary>
        /// <para>Route index of a stop/station. Can be used as a reference of the stop/station in a journeyDetail response.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Route index of a stop/station. Can be used as a reference of the stop/station in " +
            "a journeyDetail response.")]
        [System.Xml.Serialization.XmlAttributeAttribute("routeIdx", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteIdx { get; set; }
        
        /// <summary>
        /// <para>Time in format HH:MM.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Time in format HH:MM.")]
        [System.Xml.Serialization.XmlAttributeAttribute("time", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Time { get; set; }
        
        /// <summary>
        /// <para>Date in format DD.MM.YY.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Date in format DD.MM.YY.")]
        [System.Xml.Serialization.XmlAttributeAttribute("date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date { get; set; }
        
        /// <summary>
        /// <para>Track information, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Track information, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("track", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Track { get; set; }
        
        /// <summary>
        /// <para>Realtime time in format HH:MM if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime time in format HH:MM if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("rtTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RtTime { get; set; }
        
        /// <summary>
        /// <para>Realtime date in format DD.MM.YY, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime date in format DD.MM.YY, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("rtDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RtDate { get; set; }
        
        /// <summary>
        /// <para>Realtime track information, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime track information, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("rtTrack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RtTrack { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodOriginDestType
    {
        
        /// <summary>
        /// <para>Contains the name of the location.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the name of the location.")]
        string Name
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>The attribute type specifies the type of location. Valid values are ST (stop/station), ADR (address) or POI (point of interest). This attribute can be used to do some sort of classification in the user interface. For later trip requests it does not have any meaning.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"The attribute type specifies the type of location. Valid values are ST (stop/station), ADR (address) or POI (point of interest). This attribute can be used to do some sort of classification in the user interface. For later trip requests it does not have any meaning.")]
        IAttlistPeriodOriginDestTypeType Type
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Route index of a stop/station. Can be used as a reference of the stop/station in a journeyDetail response.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Route index of a stop/station. Can be used as a reference of the stop/station in " +
            "a journeyDetail response.")]
        string RouteIdx
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Time in format HH:MM.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Time in format HH:MM.")]
        string Time
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Date in format DD.MM.YY.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Date in format DD.MM.YY.")]
        string Date
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Track information, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Track information, if available.")]
        string Track
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Realtime time in format HH:MM if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime time in format HH:MM if available.")]
        string RtTime
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Realtime date in format DD.MM.YY, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime date in format DD.MM.YY, if available.")]
        string RtDate
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Realtime track information, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime track information, if available.")]
        string RtTrack
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IAttlistPeriodOriginDestTypeType", Namespace="")]
    public enum IAttlistPeriodOriginDestTypeType
    {
        
        /// <summary>
        /// </summary>
        ST,
        
        /// <summary>
        /// </summary>
        ADR,
        
        /// <summary>
        /// </summary>
        POI,
    }
    
    /// <summary>
    /// <para>The trip list contains all found trips as a result of the trip request.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The trip list contains all found trips as a result of the trip request.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TripList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TripList", Namespace="")]
    public partial class TripList : IAttlistPeriodTripList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Trip> _trip;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Trip", Namespace="")]
        public System.Collections.ObjectModel.Collection<Trip> Trip
        {
            get
            {
                return this._trip;
            }
            private set
            {
                this._trip = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Trip-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Trip collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TripSpecified
        {
            get
            {
                return (this.Trip.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TripList" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TripList" /> class.</para>
        /// </summary>
        public TripList()
        {
            this._trip = new System.Collections.ObjectModel.Collection<Trip>();
        }
        
        /// <summary>
        /// <para>If some problem occurs while calculating the trip you can find an error code here. Note: These error codes are not suitable for end users but only for reporting purposes. Most of the errors do not indicate a system failure but a reason, why no trip could be calculated for the request parameters.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"If some problem occurs while calculating the trip you can find an error code here. Note: These error codes are not suitable for end users but only for reporting purposes. Most of the errors do not indicate a system failure but a reason, why no trip could be calculated for the request parameters.")]
        [System.Xml.Serialization.XmlAttributeAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Error { get; set; }
    }
    
    /// <summary>
    /// <para>The element Trip contains all legs of the computed trip.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The element Trip contains all legs of the computed trip.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Trip", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Trip", Namespace="")]
    public partial class Trip : IAttlistPeriodTrip
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Leg> _leg;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Leg", Namespace="")]
        public System.Collections.ObjectModel.Collection<Leg> Leg
        {
            get
            {
                return this._leg;
            }
            private set
            {
                this._leg = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="Trip" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Trip" /> class.</para>
        /// </summary>
        public Trip()
        {
            this._leg = new System.Collections.ObjectModel.Collection<Leg>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _alternative = false;
        
        /// <summary>
        /// <para>The type indicates whether this is an original connection or an realtime alternative.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.ComponentModel.DescriptionAttribute("The type indicates whether this is an original connection or an realtime alternat" +
            "ive.")]
        [System.Xml.Serialization.XmlAttributeAttribute("alternative", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Alternative
        {
            get
            {
                return this._alternative;
            }
            set
            {
                this._alternative = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _valid = true;
        
        /// <summary>
        /// <para>The state indicates if the trip is still possible to ride based on the current realtime situation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.ComponentModel.DescriptionAttribute("The state indicates if the trip is still possible to ride based on the current re" +
            "altime situation.")]
        [System.Xml.Serialization.XmlAttributeAttribute("valid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Valid
        {
            get
            {
                return this._valid;
            }
            set
            {
                this._valid = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _cancelled = true;
        
        /// <summary>
        /// <para>This attribute gives information whether this journey is cancelled</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.ComponentModel.DescriptionAttribute("This attribute gives information whether this journey is cancelled")]
        [System.Xml.Serialization.XmlAttributeAttribute("cancelled", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Cancelled
        {
            get
            {
                return this._cancelled;
            }
            set
            {
                this._cancelled = value;
            }
        }
    }
    
    /// <summary>
    /// <para>A leg is one part of a trip. It can be either a walk, a bike or car ride or (in most cases) a journey by bus, train or some other means of transport.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("A leg is one part of a trip. It can be either a walk, a bike or car ride or (in m" +
        "ost cases) a journey by bus, train or some other means of transport.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Leg", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Leg", Namespace="")]
    public partial class Leg : IAttlistPeriodLeg
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Origin", Namespace="")]
        public OriginDestType Origin { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Destination", Namespace="")]
        public OriginDestType Destination { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Notes", Namespace="")]
        public Notes Notes { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("JourneyDetailRef", Namespace="")]
        public JourneyDetailRef JourneyDetailRef { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LegMessageListMessage> _messageList;
        
        /// <summary>
        /// <para>List of HIM messages</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("List of HIM messages")]
        [System.Xml.Serialization.XmlArrayAttribute("MessageList", Namespace="")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", Namespace="")]
        public System.Collections.ObjectModel.Collection<LegMessageListMessage> MessageList
        {
            get
            {
                return this._messageList;
            }
            private set
            {
                this._messageList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die MessageList-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the MessageList collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MessageListSpecified
        {
            get
            {
                return (this.MessageList.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="Leg" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Leg" /> class.</para>
        /// </summary>
        public Leg()
        {
            this._messageList = new System.Collections.ObjectModel.Collection<LegMessageListMessage>();
        }
        
        /// <summary>
        /// <para>The attribute name specifies the name of the leg (e.g. "Bus 100").</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The attribute name specifies the name of the leg (e.g. \"Bus 100\").")]
        [System.Xml.Serialization.XmlAttributeAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>The attribute type specifies the type of the leg. Valid values are IC (InterCity), LYN (Lyntog), REG (Regionaltog), S (S-Tog), TOG (other train), BUS (Bus), EXB (Express Buss), NB (Nattbus), TB (Telebus, other form of transport), F (Ferry), M (Metro) and LET (Letbane). Furthermore it can be of type WALK, BIKE and CAR if these legs are routes on the street network.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"The attribute type specifies the type of the leg. Valid values are IC (InterCity), LYN (Lyntog), REG (Regionaltog), S (S-Tog), TOG (other train), BUS (Bus), EXB (Express Buss), NB (Nattbus), TB (Telebus, other form of transport), F (Ferry), M (Metro) and LET (Letbane). Furthermore it can be of type WALK, BIKE and CAR if these legs are routes on the street network.")]
        [System.Xml.Serialization.XmlAttributeAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IAttlistPeriodLegType Type { get; set; }
    }
    
    /// <summary>
    /// <para>Contains a text with notes to be displayed for this leg.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Contains a text with notes to be displayed for this leg.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Notes", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Notes", Namespace="")]
    public partial class Notes : IAttlistPeriodNotes
    {
        
        /// <summary>
        /// <para>Text to be displayed.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Text to be displayed.")]
        [System.Xml.Serialization.XmlAttributeAttribute("text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodNotes
    {
        
        /// <summary>
        /// <para>Text to be displayed.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Text to be displayed.")]
        string Text
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// <para>Reference to journey details of this leg.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Reference to journey details of this leg.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JourneyDetailRef", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("JourneyDetailRef", Namespace="")]
    public partial class JourneyDetailRef : IAttlistPeriodJourneyDetailRef
    {
        
        /// <summary>
        /// <para>Contains a URL to call the ReST interface for journey details.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains a URL to call the ReST interface for journey details.")]
        [System.Xml.Serialization.XmlAttributeAttribute("ref", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ref { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodJourneyDetailRef
    {
        
        /// <summary>
        /// <para>Contains a URL to call the ReST interface for journey details.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains a URL to call the ReST interface for journey details.")]
        string Ref
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LegMessageList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LegMessageList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LegMessageListMessage> _message;
        
        /// <summary>
        /// <para>Single HIM message</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Single HIM message")]
        [System.Xml.Serialization.XmlElementAttribute("Message", Namespace="")]
        public System.Collections.ObjectModel.Collection<LegMessageListMessage> Message
        {
            get
            {
                return this._message;
            }
            private set
            {
                this._message = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="LegMessageList" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="LegMessageList" /> class.</para>
        /// </summary>
        public LegMessageList()
        {
            this._message = new System.Collections.ObjectModel.Collection<LegMessageListMessage>();
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LegMessageListMessage", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LegMessageListMessage
    {
        
        /// <summary>
        /// <para>Contains the header text of a HIM message</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the header text of a HIM message")]
        [System.Xml.Serialization.XmlElementAttribute("Header", Namespace="")]
        public string Header { get; set; }
        
        /// <summary>
        /// <para>Contains the message text of a HIM message</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the message text of a HIM message")]
        [System.Xml.Serialization.XmlElementAttribute("Text", Namespace="")]
        public string Text { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LegMessageListMessageLinksLink> _links;
        
        /// <summary>
        /// <para>List of links for a HIM message</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("List of links for a HIM message")]
        [System.Xml.Serialization.XmlArrayAttribute("Links", Namespace="")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Link", Namespace="")]
        public System.Collections.ObjectModel.Collection<LegMessageListMessageLinksLink> Links
        {
            get
            {
                return this._links;
            }
            private set
            {
                this._links = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Links-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Links collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinksSpecified
        {
            get
            {
                return (this.Links.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="LegMessageListMessage" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="LegMessageListMessage" /> class.</para>
        /// </summary>
        public LegMessageListMessage()
        {
            this._links = new System.Collections.ObjectModel.Collection<LegMessageListMessageLinksLink>();
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LegMessageListMessageLinks", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LegMessageListMessageLinks
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LegMessageListMessageLinksLink> _link;
        
        /// <summary>
        /// <para>Single link of a HIM message</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Single link of a HIM message")]
        [System.Xml.Serialization.XmlElementAttribute("Link", Namespace="")]
        public System.Collections.ObjectModel.Collection<LegMessageListMessageLinksLink> Link
        {
            get
            {
                return this._link;
            }
            private set
            {
                this._link = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="LegMessageListMessageLinks" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="LegMessageListMessageLinks" /> class.</para>
        /// </summary>
        public LegMessageListMessageLinks()
        {
            this._link = new System.Collections.ObjectModel.Collection<LegMessageListMessageLinksLink>();
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LegMessageListMessageLinksLink", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LegMessageListMessageLinksLink
    {
        
        /// <summary>
        /// <para>URL for a link</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("URL for a link")]
        [System.Xml.Serialization.XmlAttributeAttribute("url", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Url { get; set; }
        
        /// <summary>
        /// <para>Linktext for a link</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Linktext for a link")]
        [System.Xml.Serialization.XmlAttributeAttribute("text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodLeg
    {
        
        /// <summary>
        /// <para>The attribute name specifies the name of the leg (e.g. "Bus 100").</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The attribute name specifies the name of the leg (e.g. \"Bus 100\").")]
        string Name
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>The attribute type specifies the type of the leg. Valid values are IC (InterCity), LYN (Lyntog), REG (Regionaltog), S (S-Tog), TOG (other train), BUS (Bus), EXB (Express Buss), NB (Nattbus), TB (Telebus, other form of transport), F (Ferry), M (Metro) and LET (Letbane). Furthermore it can be of type WALK, BIKE and CAR if these legs are routes on the street network.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"The attribute type specifies the type of the leg. Valid values are IC (InterCity), LYN (Lyntog), REG (Regionaltog), S (S-Tog), TOG (other train), BUS (Bus), EXB (Express Buss), NB (Nattbus), TB (Telebus, other form of transport), F (Ferry), M (Metro) and LET (Letbane). Furthermore it can be of type WALK, BIKE and CAR if these legs are routes on the street network.")]
        IAttlistPeriodLegType Type
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IAttlistPeriodLegType", Namespace="")]
    public enum IAttlistPeriodLegType
    {
        
        /// <summary>
        /// </summary>
        IC,
        
        /// <summary>
        /// </summary>
        LYN,
        
        /// <summary>
        /// </summary>
        REG,
        
        /// <summary>
        /// </summary>
        S,
        
        /// <summary>
        /// </summary>
        TOG,
        
        /// <summary>
        /// </summary>
        BUS,
        
        /// <summary>
        /// </summary>
        EXB,
        
        /// <summary>
        /// </summary>
        NB,
        
        /// <summary>
        /// </summary>
        TB,
        
        /// <summary>
        /// </summary>
        F,
        
        /// <summary>
        /// </summary>
        M,
        
        /// <summary>
        /// </summary>
        LET,
        
        /// <summary>
        /// </summary>
        WALK,
        
        /// <summary>
        /// </summary>
        BIKE,
        
        /// <summary>
        /// </summary>
        CAR,
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodTrip
    {
        
        /// <summary>
        /// <para>The type indicates whether this is an original connection or an realtime alternative.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.ComponentModel.DescriptionAttribute("The type indicates whether this is an original connection or an realtime alternat" +
            "ive.")]
        bool Alternative
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>The state indicates if the trip is still possible to ride based on the current realtime situation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.ComponentModel.DescriptionAttribute("The state indicates if the trip is still possible to ride based on the current re" +
            "altime situation.")]
        bool Valid
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>This attribute gives information whether this journey is cancelled</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.ComponentModel.DescriptionAttribute("This attribute gives information whether this journey is cancelled")]
        bool Cancelled
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodTripList
    {
        
        /// <summary>
        /// <para>If some problem occurs while calculating the trip you can find an error code here. Note: These error codes are not suitable for end users but only for reporting purposes. Most of the errors do not indicate a system failure but a reason, why no trip could be calculated for the request parameters.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"If some problem occurs while calculating the trip you can find an error code here. Note: These error codes are not suitable for end users but only for reporting purposes. Most of the errors do not indicate a system failure but a reason, why no trip could be calculated for the request parameters.")]
        string Error
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// <para>The element RKTariffXML contains all tariff information for the computed trip</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The element RKTariffXML contains all tariff information for the computed trip")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RKTariffXML", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("RKTariffXML", Namespace="")]
    public partial class RKTariffXML
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RKTariffXMLGeneric> _generic;
        
        /// <summary>
        /// <para>The element generic contains infotexts with generic information for all princingSets.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The element generic contains infotexts with generic information for all princingS" +
            "ets.")]
        [System.Xml.Serialization.XmlElementAttribute("generic", Namespace="")]
        public System.Collections.ObjectModel.Collection<RKTariffXMLGeneric> Generic
        {
            get
            {
                return this._generic;
            }
            private set
            {
                this._generic = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Generic-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Generic collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenericSpecified
        {
            get
            {
                return (this.Generic.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RKTariffXML" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RKTariffXML" /> class.</para>
        /// </summary>
        public RKTariffXML()
        {
            this._generic = new System.Collections.ObjectModel.Collection<RKTariffXMLGeneric>();
            this._pricingSet = new System.Collections.ObjectModel.Collection<RKTariffXMLPricingSet>();
            this._error = new System.Collections.ObjectModel.Collection<RKTariffXMLError>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RKTariffXMLPricingSet> _pricingSet;
        
        /// <summary>
        /// <para>The element princingSet contains all princings for the computed trip.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The element princingSet contains all princings for the computed trip.")]
        [System.Xml.Serialization.XmlElementAttribute("pricingSet", Namespace="")]
        public System.Collections.ObjectModel.Collection<RKTariffXMLPricingSet> PricingSet
        {
            get
            {
                return this._pricingSet;
            }
            private set
            {
                this._pricingSet = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die PricingSet-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the PricingSet collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PricingSetSpecified
        {
            get
            {
                return (this.PricingSet.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RKTariffXMLError> _error;
        
        /// <summary>
        /// <para>The element error contains one attribute with an error code</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The element error contains one attribute with an error code")]
        [System.Xml.Serialization.XmlElementAttribute("error", Namespace="")]
        public System.Collections.ObjectModel.Collection<RKTariffXMLError> Error
        {
            get
            {
                return this._error;
            }
            private set
            {
                this._error = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Error-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Error collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorSpecified
        {
            get
            {
                return (this.Error.Count != 0);
            }
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RKTariffXMLGeneric", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RKTariffXMLGeneric
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RKTariffXMLGenericInfotext> _infotext;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("infotext", Namespace="")]
        public System.Collections.ObjectModel.Collection<RKTariffXMLGenericInfotext> Infotext
        {
            get
            {
                return this._infotext;
            }
            private set
            {
                this._infotext = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Infotext-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Infotext collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfotextSpecified
        {
            get
            {
                return (this.Infotext.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RKTariffXMLGeneric" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RKTariffXMLGeneric" /> class.</para>
        /// </summary>
        public RKTariffXMLGeneric()
        {
            this._infotext = new System.Collections.ObjectModel.Collection<RKTariffXMLGenericInfotext>();
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RKTariffXMLGenericInfotext", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RKTariffXMLGenericInfotext
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RKTariffXMLPricingSet", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RKTariffXMLPricingSet
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RKTariffXMLPricingSetPricing> _pricing;
        
        /// <summary>
        /// <para>The element princing contains all tickets for every available discount level.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The element princing contains all tickets for every available discount level.")]
        [System.Xml.Serialization.XmlElementAttribute("pricing", Namespace="")]
        public System.Collections.ObjectModel.Collection<RKTariffXMLPricingSetPricing> Pricing
        {
            get
            {
                return this._pricing;
            }
            private set
            {
                this._pricing = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RKTariffXMLPricingSet" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RKTariffXMLPricingSet" /> class.</para>
        /// </summary>
        public RKTariffXMLPricingSet()
        {
            this._pricing = new System.Collections.ObjectModel.Collection<RKTariffXMLPricingSetPricing>();
        }
        
        /// <summary>
        /// <para>The amount of passengers used for the tariff calculation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The amount of passengers used for the tariff calculation.")]
        [System.Xml.Serialization.XmlAttributeAttribute("passengerTypeAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PassengerTypeAmount { get; set; }
        
        /// <summary>
        /// <para>This attribute only shows a plain text information referring to the attribute passenger TypeID</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("This attribute only shows a plain text information referring to the attribute pas" +
            "senger TypeID")]
        [System.Xml.Serialization.XmlAttributeAttribute("passengerTypeInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PassengerTypeInfo { get; set; }
        
        /// <summary>
        /// <para>This attribute indicates the type of the passenger</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("This attribute indicates the type of the passenger")]
        [System.Xml.Serialization.XmlAttributeAttribute("passengerTypeId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PassengerTypeId { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RKTariffXMLPricingSetPricing", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RKTariffXMLPricingSetPricing
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RKTariffXMLPricingSetPricingTicket> _ticket;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ticket", Namespace="")]
        public System.Collections.ObjectModel.Collection<RKTariffXMLPricingSetPricingTicket> Ticket
        {
            get
            {
                return this._ticket;
            }
            private set
            {
                this._ticket = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RKTariffXMLPricingSetPricing" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RKTariffXMLPricingSetPricing" /> class.</para>
        /// </summary>
        public RKTariffXMLPricingSetPricing()
        {
            this._ticket = new System.Collections.ObjectModel.Collection<RKTariffXMLPricingSetPricingTicket>();
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("discountLevel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DiscountLevel { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RKTariffXMLPricingSetPricingTicket", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RKTariffXMLPricingSetPricingTicket
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("price", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Price { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("tariff", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tariff { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RKTariffXMLError", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RKTariffXMLError
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Code { get; set; }
    }
    
    /// <summary>
    /// <para>Destination of a leg including location name, location type, location route index (if available), arrival time and date, realtime arrival time (if available), track and realtime track (if available)</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Destination of a leg including location name, location type, location route index" +
        " (if available), arrival time and date, realtime arrival time (if available), tr" +
        "ack and realtime track (if available)")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Destination", Namespace="")]
    public partial class Destination : OriginDestType
    {
    }
}
