//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.206.0.
namespace MBW.Clients.Rejseplanen.Schema.RestJourneyDetail
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>The journey details contain a list of stops/stations and notes. They also contain the journeys names and types.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The journey details contain a list of stops/stations and notes. They also contain" +
        " the journeys names and types.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JourneyDetail", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("JourneyDetail", Namespace="")]
    public partial class JourneyDetail
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Stop> _stop;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Stop", Namespace="")]
        public System.Collections.ObjectModel.Collection<Stop> Stop
        {
            get
            {
                return this._stop;
            }
            private set
            {
                this._stop = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="JourneyDetail" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="JourneyDetail" /> class.</para>
        /// </summary>
        public JourneyDetail()
        {
            this._stop = new System.Collections.ObjectModel.Collection<Stop>();
            this._journeyName = new System.Collections.ObjectModel.Collection<JourneyName>();
            this._journeyType = new System.Collections.ObjectModel.Collection<JourneyType>();
            this._note = new System.Collections.ObjectModel.Collection<Note>();
            this._messageList = new System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessage>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JourneyName> _journeyName;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("JourneyName", Namespace="")]
        public System.Collections.ObjectModel.Collection<JourneyName> JourneyName
        {
            get
            {
                return this._journeyName;
            }
            private set
            {
                this._journeyName = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JourneyType> _journeyType;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("JourneyType", Namespace="")]
        public System.Collections.ObjectModel.Collection<JourneyType> JourneyType
        {
            get
            {
                return this._journeyType;
            }
            private set
            {
                this._journeyType = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Note> _note;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace="")]
        public System.Collections.ObjectModel.Collection<Note> Note
        {
            get
            {
                return this._note;
            }
            private set
            {
                this._note = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Note-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Note collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoteSpecified
        {
            get
            {
                return (this.Note.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessage> _messageList;
        
        /// <summary>
        /// <para>List of HIM messages</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("List of HIM messages")]
        [System.Xml.Serialization.XmlArrayAttribute("MessageList", Namespace="")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", Namespace="")]
        public System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessage> MessageList
        {
            get
            {
                return this._messageList;
            }
            private set
            {
                this._messageList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die MessageList-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the MessageList collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MessageListSpecified
        {
            get
            {
                return (this.MessageList.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("JourneyChange", Namespace="")]
        public JourneyDetailJourneyChange JourneyChange { get; set; }
    }
    
    /// <summary>
    /// <para>The element Stop contains the name of the stop/station, the route index, the x coordinate, the y coordinate, the departure time and date, the arrival time and date, the track, the realtime departure time and date, the realtime arrival time and date and the realtime track.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"The element Stop contains the name of the stop/station, the route index, the x coordinate, the y coordinate, the departure time and date, the arrival time and date, the track, the realtime departure time and date, the realtime arrival time and date and the realtime track.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Stop", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Stop", Namespace="")]
    public partial class Stop : IAttlistPeriodStop
    {
        
        /// <summary>
        /// <para>Contains the name of the stop/station.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the name of the stop/station.")]
        [System.Xml.Serialization.XmlAttributeAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>Route index of a stop/station. Can be used as a reference of the stop/station in a journeyDetail response.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Route index of a stop/station. Can be used as a reference of the stop/station in " +
            "a journeyDetail response.")]
        [System.Xml.Serialization.XmlAttributeAttribute("routeIdx", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteIdx { get; set; }
        
        /// <summary>
        /// <para>The x coordinate as integer in WGS84 multiplied with 1,000,000</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The x coordinate as integer in WGS84 multiplied with 1,000,000")]
        [System.Xml.Serialization.XmlAttributeAttribute("x", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string X { get; set; }
        
        /// <summary>
        /// <para>The y coordinate as integer in WGS84 multiplied with 1,000,000</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The y coordinate as integer in WGS84 multiplied with 1,000,000")]
        [System.Xml.Serialization.XmlAttributeAttribute("y", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Y { get; set; }
        
        /// <summary>
        /// <para>Departure time in format HH:MM, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Departure time in format HH:MM, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("depTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DepTime { get; set; }
        
        /// <summary>
        /// <para>Departure date in format DD.MM.YY, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Departure date in format DD.MM.YY, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("depDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DepDate { get; set; }
        
        /// <summary>
        /// <para>Arrival time in format HH:MM, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Arrival time in format HH:MM, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("arrTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArrTime { get; set; }
        
        /// <summary>
        /// <para>Arrival date in format DD.MM.YY, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Arrival date in format DD.MM.YY, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("arrDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArrDate { get; set; }
        
        /// <summary>
        /// <para>Track information, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Track information, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("track", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Track { get; set; }
        
        /// <summary>
        /// <para>Realtime departure time in format HH:MM if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime departure time in format HH:MM if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("rtDepTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RtDepTime { get; set; }
        
        /// <summary>
        /// <para>Realtime departure date in format DD.MM.YY, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime departure date in format DD.MM.YY, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("rtDepDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RtDepDate { get; set; }
        
        /// <summary>
        /// <para>Realtime arrival time in format HH:MM if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime arrival time in format HH:MM if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("rtArrTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RtArrTime { get; set; }
        
        /// <summary>
        /// <para>Realtime arrival date in format DD.MM.YY, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime arrival date in format DD.MM.YY, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("rtArrDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RtArrDate { get; set; }
        
        /// <summary>
        /// <para>Realtime track information, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime track information, if available.")]
        [System.Xml.Serialization.XmlAttributeAttribute("rtTrack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RtTrack { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodStop
    {
        
        /// <summary>
        /// <para>Contains the name of the stop/station.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the name of the stop/station.")]
        string Name
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Route index of a stop/station. Can be used as a reference of the stop/station in a journeyDetail response.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Route index of a stop/station. Can be used as a reference of the stop/station in " +
            "a journeyDetail response.")]
        string RouteIdx
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>The x coordinate as integer in WGS84 multiplied with 1,000,000</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The x coordinate as integer in WGS84 multiplied with 1,000,000")]
        string X
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>The y coordinate as integer in WGS84 multiplied with 1,000,000</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The y coordinate as integer in WGS84 multiplied with 1,000,000")]
        string Y
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Departure time in format HH:MM, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Departure time in format HH:MM, if available.")]
        string DepTime
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Departure date in format DD.MM.YY, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Departure date in format DD.MM.YY, if available.")]
        string DepDate
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Arrival time in format HH:MM, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Arrival time in format HH:MM, if available.")]
        string ArrTime
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Arrival date in format DD.MM.YY, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Arrival date in format DD.MM.YY, if available.")]
        string ArrDate
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Track information, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Track information, if available.")]
        string Track
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Realtime departure time in format HH:MM if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime departure time in format HH:MM if available.")]
        string RtDepTime
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Realtime departure date in format DD.MM.YY, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime departure date in format DD.MM.YY, if available.")]
        string RtDepDate
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Realtime arrival time in format HH:MM if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime arrival time in format HH:MM if available.")]
        string RtArrTime
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Realtime arrival date in format DD.MM.YY, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime arrival date in format DD.MM.YY, if available.")]
        string RtArrDate
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Realtime track information, if available.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Realtime track information, if available.")]
        string RtTrack
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// <para>Contains name of journey.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Contains name of journey.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JourneyName", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("JourneyName", Namespace="")]
    public partial class JourneyName : IAttlistPeriodJourneyName
    {
        
        /// <summary>
        /// <para>Name to be displayed.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Name to be displayed.")]
        [System.Xml.Serialization.XmlAttributeAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>Start of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Start of validity on total route.")]
        [System.Xml.Serialization.XmlAttributeAttribute("routeIdxFrom", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteIdxFrom { get; set; }
        
        /// <summary>
        /// <para>End of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("End of validity on total route.")]
        [System.Xml.Serialization.XmlAttributeAttribute("routeIdxTo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteIdxTo { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodJourneyName
    {
        
        /// <summary>
        /// <para>Name to be displayed.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Name to be displayed.")]
        string Name
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Start of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Start of validity on total route.")]
        string RouteIdxFrom
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>End of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("End of validity on total route.")]
        string RouteIdxTo
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// <para>Contains type of journey.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Contains type of journey.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JourneyType", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("JourneyType", Namespace="")]
    public partial class JourneyType : IAttlistPeriodJourneyType
    {
        
        /// <summary>
        /// <para>The attribute type specifies the type of the journey. Valid values are IC (InterCity), LYN (Lyntog), REG (Regionaltog), S (S-Tog), TOG (other train), BUS (Bus), EXB (Express Buss), NB (Nattbus), TB (Telebus, other form of transport), F (Ferry), M (Metro) and LET (Letbane).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"The attribute type specifies the type of the journey. Valid values are IC (InterCity), LYN (Lyntog), REG (Regionaltog), S (S-Tog), TOG (other train), BUS (Bus), EXB (Express Buss), NB (Nattbus), TB (Telebus, other form of transport), F (Ferry), M (Metro) and LET (Letbane).")]
        [System.Xml.Serialization.XmlAttributeAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IAttlistPeriodJourneyTypeType Type { get; set; }
        
        /// <summary>
        /// <para>Start of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Start of validity on total route.")]
        [System.Xml.Serialization.XmlAttributeAttribute("routeIdxFrom", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteIdxFrom { get; set; }
        
        /// <summary>
        /// <para>End of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("End of validity on total route.")]
        [System.Xml.Serialization.XmlAttributeAttribute("routeIdxTo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteIdxTo { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodJourneyType
    {
        
        /// <summary>
        /// <para>The attribute type specifies the type of the journey. Valid values are IC (InterCity), LYN (Lyntog), REG (Regionaltog), S (S-Tog), TOG (other train), BUS (Bus), EXB (Express Buss), NB (Nattbus), TB (Telebus, other form of transport), F (Ferry), M (Metro) and LET (Letbane).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"The attribute type specifies the type of the journey. Valid values are IC (InterCity), LYN (Lyntog), REG (Regionaltog), S (S-Tog), TOG (other train), BUS (Bus), EXB (Express Buss), NB (Nattbus), TB (Telebus, other form of transport), F (Ferry), M (Metro) and LET (Letbane).")]
        IAttlistPeriodJourneyTypeType Type
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Start of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Start of validity on total route.")]
        string RouteIdxFrom
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>End of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("End of validity on total route.")]
        string RouteIdxTo
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IAttlistPeriodJourneyTypeType", Namespace="")]
    public enum IAttlistPeriodJourneyTypeType
    {
        
        /// <summary>
        /// </summary>
        IC,
        
        /// <summary>
        /// </summary>
        LYN,
        
        /// <summary>
        /// </summary>
        REG,
        
        /// <summary>
        /// </summary>
        S,
        
        /// <summary>
        /// </summary>
        TOG,
        
        /// <summary>
        /// </summary>
        BUS,
        
        /// <summary>
        /// </summary>
        EXB,
        
        /// <summary>
        /// </summary>
        NB,
        
        /// <summary>
        /// </summary>
        TB,
        
        /// <summary>
        /// </summary>
        F,
        
        /// <summary>
        /// </summary>
        M,
        
        /// <summary>
        /// </summary>
        LET,
    }
    
    /// <summary>
    /// <para>Contains a text with notes to be displayed for this leg.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Contains a text with notes to be displayed for this leg.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Note", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Note", Namespace="")]
    public partial class Note : IAttlistPeriodNote
    {
        
        /// <summary>
        /// <para>Text to be displayed.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Text to be displayed.")]
        [System.Xml.Serialization.XmlAttributeAttribute("text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
        
        /// <summary>
        /// <para>Start of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Start of validity on total route.")]
        [System.Xml.Serialization.XmlAttributeAttribute("routeIdxFrom", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteIdxFrom { get; set; }
        
        /// <summary>
        /// <para>End of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("End of validity on total route.")]
        [System.Xml.Serialization.XmlAttributeAttribute("routeIdxTo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteIdxTo { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    public partial interface IAttlistPeriodNote
    {
        
        /// <summary>
        /// <para>Text to be displayed.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Text to be displayed.")]
        string Text
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Start of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Start of validity on total route.")]
        string RouteIdxFrom
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>End of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("End of validity on total route.")]
        string RouteIdxTo
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JourneyDetailMessageList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JourneyDetailMessageList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessage> _message;
        
        /// <summary>
        /// <para>Single HIM message</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Single HIM message")]
        [System.Xml.Serialization.XmlElementAttribute("Message", Namespace="")]
        public System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessage> Message
        {
            get
            {
                return this._message;
            }
            private set
            {
                this._message = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="JourneyDetailMessageList" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="JourneyDetailMessageList" /> class.</para>
        /// </summary>
        public JourneyDetailMessageList()
        {
            this._message = new System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessage>();
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JourneyDetailMessageListMessage", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JourneyDetailMessageListMessage
    {
        
        /// <summary>
        /// <para>Contains the header text of a HIM message</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the header text of a HIM message")]
        [System.Xml.Serialization.XmlElementAttribute("Header", Namespace="")]
        public string Header { get; set; }
        
        /// <summary>
        /// <para>Contains the message text of a HIM message</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains the message text of a HIM message")]
        [System.Xml.Serialization.XmlElementAttribute("Text", Namespace="")]
        public string Text { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessageLinksLink> _links;
        
        /// <summary>
        /// <para>List of links for a HIM message</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("List of links for a HIM message")]
        [System.Xml.Serialization.XmlArrayAttribute("Links", Namespace="")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Link", Namespace="")]
        public System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessageLinksLink> Links
        {
            get
            {
                return this._links;
            }
            private set
            {
                this._links = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Links-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Links collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinksSpecified
        {
            get
            {
                return (this.Links.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="JourneyDetailMessageListMessage" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="JourneyDetailMessageListMessage" /> class.</para>
        /// </summary>
        public JourneyDetailMessageListMessage()
        {
            this._links = new System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessageLinksLink>();
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JourneyDetailMessageListMessageLinks", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JourneyDetailMessageListMessageLinks
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessageLinksLink> _link;
        
        /// <summary>
        /// <para>Single link of a HIM message</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Single link of a HIM message")]
        [System.Xml.Serialization.XmlElementAttribute("Link", Namespace="")]
        public System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessageLinksLink> Link
        {
            get
            {
                return this._link;
            }
            private set
            {
                this._link = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="JourneyDetailMessageListMessageLinks" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="JourneyDetailMessageListMessageLinks" /> class.</para>
        /// </summary>
        public JourneyDetailMessageListMessageLinks()
        {
            this._link = new System.Collections.ObjectModel.Collection<JourneyDetailMessageListMessageLinksLink>();
        }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JourneyDetailMessageListMessageLinksLink", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JourneyDetailMessageListMessageLinksLink
    {
        
        /// <summary>
        /// <para>URL for a link</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("URL for a link")]
        [System.Xml.Serialization.XmlAttributeAttribute("url", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Url { get; set; }
        
        /// <summary>
        /// <para>Linktext for a link</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Linktext for a link")]
        [System.Xml.Serialization.XmlAttributeAttribute("text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Text { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.206.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JourneyDetailJourneyChange", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JourneyDetailJourneyChange
    {
        
        /// <summary>
        /// <para>Contains a text with change information for this journeydetail. Possible values are: CANCELLATION, DEACTIVATION, ACTIVATION and NEW</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Contains a text with change information for this journeydetail. Possible values a" +
            "re: CANCELLATION, DEACTIVATION, ACTIVATION and NEW")]
        [System.Xml.Serialization.XmlAttributeAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        /// <summary>
        /// <para>Start of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Start of validity on total route.")]
        [System.Xml.Serialization.XmlAttributeAttribute("routeIdxFrom", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteIdxFrom { get; set; }
        
        /// <summary>
        /// <para>End of validity on total route.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("End of validity on total route.")]
        [System.Xml.Serialization.XmlAttributeAttribute("routeIdxTo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteIdxTo { get; set; }
    }
}
